In [4]:
import pandas as pd
import matplotlib as mpl  
%matplotlib inline
import numpy as np
import statsmodels.formula.api as smf
import datetime as dt

In [98]:
Table1 = pd.read_csv('mrc_table1.csv')
Table2 = pd.read_csv('mrc_table2.csv')
Table10 = pd.read_csv('mrc_table10.csv')
Table11 = pd.read_csv('mrc_table11.csv')

In [99]:
Table_merge=Table1.merge(Table2, on='super_opeid', how='left')
Table_merge=Table_merge.merge(Table10)

In [152]:
Table2.columns

Index(['super_opeid', 'name', 'type', 'tier', 'tier_name', 'iclevel', 'region',
       'state', 'cz', 'czname', 'cfips', 'county', 'multi', 'count', 'female',
       'k_married', 'mr_kq5_pq1', 'mr_ktop1_pq1', 'par_mean', 'par_median',
       'par_rank', 'par_q1', 'par_q2', 'par_q3', 'par_q4', 'par_q5',
       'par_top10pc', 'par_top5pc', 'par_top1pc', 'par_toppt1pc', 'k_rank',
       'k_mean', 'k_median', 'k_median_nozero', 'k_0inc', 'k_q1', 'k_q2',
       'k_q3', 'k_q4', 'k_q5', 'k_top10pc', 'k_top5pc', 'k_top1pc',
       'k_rank_cond_parq1', 'k_rank_cond_parq2', 'k_rank_cond_parq3',
       'k_rank_cond_parq4', 'k_rank_cond_parq5', 'kq1_cond_parq1',
       'kq2_cond_parq1', 'kq3_cond_parq1', 'kq4_cond_parq1', 'kq5_cond_parq1',
       'kq1_cond_parq2', 'kq2_cond_parq2', 'kq3_cond_parq2', 'kq4_cond_parq2',
       'kq5_cond_parq2', 'kq1_cond_parq3', 'kq2_cond_parq3', 'kq3_cond_parq3',
       'kq4_cond_parq3', 'kq5_cond_parq3', 'kq1_cond_parq4', 'kq2_cond_parq4',
       'kq3_cond_parq4', 'kq4_cond_parq4', 'kq5_cond_parq4', 'kq1_cond_parq5',
       'kq2_cond_parq5', 'kq3_cond_parq5', 'kq4_cond_parq5', 'kq5_cond_parq5',
       'ktop1pc_cond_parq1', 'ktop1pc_cond_parq2', 'ktop1pc_cond_parq3',
       'ktop1pc_cond_parq4', 'ktop1pc_cond_parq5', 'k_married_cond_parq1',
       'k_married_cond_parq2', 'k_married_cond_parq3', 'k_married_cond_parq4',
       'k_married_cond_parq5', 'shareimputed', 'imputed'],
      dtype='object')

In [101]:
Table10.columns

Index(['super_opeid', 'name', 'region', 'state', 'fips', 'cz', 'czname',
       'cfips', 'county', 'zip', 'tier', 'tier_name', 'type', 'iclevel',
       'public', 'barrons', 'exp_instr_pc_2000', 'exp_instr_pc_2013', 'multi',
       'hbcu', 'flagship', 'ipeds_enrollment_2013', 'ipeds_enrollment_2000',
       'sticker_price_2013', 'sticker_price_2000', 'grad_rate_150_p_2013',
       'grad_rate_150_p_2002', 'avgfacsal_2013', 'avgfacsal_2001',
       'sat_avg_2013', 'sat_avg_2001', 'scorecard_netprice_2013',
       'scorecard_rej_rate_2013', 'scorecard_median_earnings_2011',
       'endowment_pc_2000', 'exp_instr_2012', 'exp_instr_2000',
       'asian_or_pacific_share_fall_2000', 'black_share_fall_2000',
       'hisp_share_fall_2000', 'alien_share_fall_2000', 'pct_arthuman_2000',
       'pct_business_2000', 'pct_health_2000', 'pct_multidisci_2000',
       'pct_publicsocial_2000', 'pct_stem_2000', 'pct_socialscience_2000',
       'pct_tradepersonal_2000'],
      dtype='object')

In [187]:
Table_A=Table_merge[['super_opeid','name_x','czname_x','zip','state_x','region','type', 'public','iclevel',
             'tier', 'tier_name','barrons',
             'female','multi',
             'scorecard_rej_rate_2013','avgfacsal_2013','ipeds_enrollment_2013','grad_rate_150_p_2013','exp_instr_pc_2013',
             'k_median_x','k_mean','k_rank']]

In [194]:
Table_A.count()

super_opeid                2199
name_x                     2199
czname_x                   2199
zip                        2199
state_x                    2199
region                     2199
type                       2199
public                     2199
iclevel                    2199
tier                       2199
tier_name                  2199
barrons                    2199
female                     2180
multi                      2199
scorecard_rej_rate_2013    1232
avgfacsal_2013             2128
ipeds_enrollment_2013      2199
grad_rate_150_p_2013       2027
exp_instr_pc_2013          2193
k_median_x                 2199
k_mean                     2199
k_rank                     2199
dtype: int64

In [149]:
Table_A.dropna()

,name_x,czname_x,state_x,region,type,public,iclevel,tier,tier_name,barrons,female,multi,scorecard_rej_rate_2013,avgfacsal_2013,ipeds_enrollment_2013,grad_rate_150_p_2013,exp_instr_pc_2013,k_median_x,k_mean,k_rank
0,Vaughn College Of Aeronautics And Technology,New York,NY,1.0,2.0,0,1.0,8,Nonselective four-year private not-for-profit,9,0.099518,0.0,0.229400,9139.0000,1724,0.555556,5508.3994,53000,56313.276516,0.669554
2,City College Of New York - CUNY,New York,NY,1.0,1.0,1,1.0,5,Selective public,4,0.472238,0.0,0.659000,8257.0000,12501,0.476538,9341.7002,48500,60889.663557,0.659947
4,"California State University, Los Angeles",Los Angeles,CA,4.0,1.0,1,1.0,5,Selective public,4,0.624470,0.0,0.324800,8767.0000,19589,0.356537,4761.4780,43000,44225.554132,0.615710
6,MCPHS University,Boston,MA,1.0,2.0,0,1.0,8,Nonselective four-year private not-for-profit,9,0.706052,0.0,0.107900,8066.0000,3897,0.617450,9287.2422,112700,107741.835938,0.857008
7,Pace University,New York,NY,1.0,2.0,0,1.0,6,Selective private,4,0.595074,0.0,0.231700,11627.0000,8289,0.514639,9327.0703,60700,68356.636178,0.705232
8,State University Of New York At Stony Brook,New York,NY,1.0,1.0,1,1.0,3,Highly selective public,2,0.495815,0.0,0.605200,10346.0000,15992,0.659297,15185.5980,60100,65407.727703,0.708213
11,Texas A&M International University,Laredo,TX,3.0,1.0,1,1.0,7,Nonselective four-year public,999,0.610465,0.0,0.521500,7689.0000,6585,0.429752,3503.4050,42800,44043.149851,0.620142
22,"California State Polytechnic University, Pomona",Los Angeles,CA,4.0,1.0,1,1.0,5,Selective public,4,0.420134,0.0,0.478200,9101.0000,20952,0.523726,5185.8892,55100,58449.621144,0.687875
25,"Saint John's University of Queens, NY",New York,NY,1.0,2.0,0,1.0,6,Selective private,4,0.562482,0.0,0.468400,11777.0000,15773,0.557262,7481.4761,58900,66248.341935,0.698639
26,"University Of California, Irvine",Los Angeles,CA,4.0,1.0,1,1.0,3,Highly selective public,2,0.529847,0.0,0.576100,12839.0000,23530,0.858450,18460.7890,60400,68174.468984,0.705837
31,Saint Francis College,New York,NY,1.0,2.0,0,1.0,6,Selective private,5,0.552007,0.0,0.356700,8739.0000,2764,0.520921,4986.2578,53000,56786.843964,0.672688
33,New Jersey Institute Of Technology,Newark,NJ,1.0,1.0,1,1.0,5,Selective public,3,0.198585,0.0,0.345300,11262.0000,7317,0.576712,7870.3740,71600,74319.956003,0.765165
34,Mount St. Mary's College,Los Angeles,CA,4.0,2.0,0,1.0,6,Selective private,4,0.988006,0.0,0.259100,8055.0000,2625,0.655556,6333.2393,44900,48089.914092,0.639920
35,Woodbury University,Los Angeles,CA,4.0,2.0,0,1.0,6,Selective private,5,0.610951,0.0,0.442500,9365.0000,1357,0.446541,11264.1800,44300,45386.350459,0.618991
36,"California State University, Northridge",Los Angeles,CA,4.0,1.0,1,1.0,5,Selective public,5,0.586290,0.0,0.537600,8395.0000,33771,0.457516,4898.8613,44100,49244.333410,0.623090
40,Bloomfield College,Newark,NJ,1.0,2.0,0,1.0,6,Selective private,4,0.612335,0.0,0.453600,7807.0000,1972,0.364217,7222.5869,35600,39703.290347,0.571393
41,"University Of California, Riverside",Los Angeles,CA,4.0,1.0,1,1.0,5,Selective public,4,0.550402,0.0,0.380000,11324.0000,18621,0.661713,9961.1396,52800,59668.700686,0.673729
43,College Of Mount Saint Vincent And Manhattan C...,New York,NY,1.0,2.0,0,1.0,6,Selective private,3,0.550542,1.0,0.315496,8715.2422,5072,0.664217,7912.6499,67900,72427.471354,0.731684
47,"California State University, Dominguez Hills",Los Angeles,CA,4.0,1.0,1,1.0,5,Selective public,5,0.697194,0.0,0.425300,8202.0000,12481,0.293538,4221.8442,40300,42627.001786,0.600814
48,"University Of California, Los Angeles",Los Angeles,CA,4.0,1.0,1,1.0,2,Other elite schools (public and private),1,0.560203,0.0,0.780100,15089.0000,28674,0.903113,38861.6840,65800,82856.588005,0.723795
51,Long Island University System,New York,NY,1.0,2.0,0,1.0,6,Selective private,4,0.650964,1.0,0.169289,10426.6150,13068,0.328618,7943.7056,39900,46372.923504,0.601018
53,Saint Peter's University,Newark,NJ,1.0,2.0,0,1.0,6,Selective private,5,0.487714,0.0,0.459200,8274.0000,2484,0.533214,6591.0952,45500,50442.787864,0.635548
54,San Jose State University,San Jose,CA,4.0,1.0,1,1.0,5,Selective public,4,0.507561,0.0,0.365300,9155.0000,25862,0.480906,5421.9053,56500,64343.154911,0.698803
56,New Jersey City University,Newark,NJ,1.0,1.0,1,1.0,5,Selective public,4,0.559762,0.0,0.587100,9101.0000,6437,0.317411,7012.4287,41200,43979.970496,0.607149
57,Texas A&M University - Kingsville,Corpus Christi,TX,3.0,1.0,1,1.0,5,Selective public,5,0.439854,0.0,0.119000,7392.0000,9430,0.341014,4459.4521,39800,47080.097359,0.607279
58,Xavier University Of Louisiana,New Orleans,LA,3.0,2.0,0,1.0,6,Selective private,4,0.729716,0.0,0.455700,8252.0000,2504,0.478448,7533.9409,48400,63788.146819,0.673897
59,Sul Ross State University,Alpine,TX,3.0,1.0,1,1.0,5,Selective public,5,0.445093,0.0,0.478000,6180.0000,2003,0.279167,4827.2124,37100,40458.828203,0.574173
60,Tuskegee University,Auburn,AL,3.0,2.0,0,1.0,6,Selective private,4,0.578444,0.0,0.648900,6679.0000,2584,0.438442,11172.3020,38900,43675.605708,0.604271
61,Florida International University,Miami,FL,3.0,1.0,1,1.0,5,Selective public,3,0.574097,0.0,0.569600,9653.0000,39142,0.516099,5691.3062,46800,52704.924479,0.640972
62,Saint Mary's University,San Antonio,TX,3.0,2.0,0,1.0,6,Selective private,4,0.598173,0.0,0.417700,9441.0000,2393,0.550442,8690.2314,49700,57557.506076,0.679853
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2126,Kentucky Christian University,Huntington,KY,3.0,2.0,0,1.0,6,Selective private,5,0.533046,0.0,0.486400,4594.0000,559,0.386503,4338.2334,33400,31889.851849,0.504568
2127,Hanover College,Madison,IN,2.0,2.0,0,1.0,6,Selective private,3,0.549296,0.0,0.332700,7847.0000,1163,0.718615,11974.1860,46300,54352.503316,0.657553
2128,Trevecca Nazarene University,Nashville,TN,3.0,2.0,0,1.0,6,Selective private,3,0.569558,0.0,0.228000,6337.0000,1492,0.466387,5980.0674,34000,37206.004993,0.553355
2131,Davidson College,Charlotte,NC,3.0,2.0,0,1.0,2,Other elite schools (public and private),1,0.517101,0.0,0.743900,11706.0000,1788,0.924569,17948.5270,60300,91436.980119,0.715114
2134,Johnson University,Knoxville,TN,3.0,2.0,0,1.0,8,Nonselective four-year private not-for-profit,999,0.508121,0.0,0.453600,5485.0000,830,0.572289,5040.1372,29400,29699.278304,0.501795
2135,Cincinnati Christian University,Cincinnati,OH,2.0,2.0,0,1.0,8,Nonselective four-year private not-for-profit,999,0.493213,0.0,0.360200,5323.0000,676,0.388889,4683.0596,30100,34284.151693,0.535405
2140,Colorado Christian University,Denver,CO,4.0,2.0,0,1.0,6,Selective private,3,0.603825,0.0,0.023600,5817.0000,4973,0.369668,3677.7090,30700,37368.020833,0.536570
2142,Newman University,Wichita,KS,2.0,2.0,0,1.0,6,Selective private,4,0.615385,0.0,0.552800,5684.0000,2795,0.518797,2883.9980,45700,49570.567708,0.643032
2143,Dordt College,Sioux Center,IA,2.0,2.0,0,1.0,6,Selective private,3,0.565502,0.0,0.245800,5959.0000,1376,0.616216,8759.2871,35400,42434.759877,0.560324
2145,Oakland City University,Evansville,IN,2.0,2.0,0,1.0,6,Selective private,5,0.508143,0.0,0.271500,3610.0000,2311,0.703226,2428.1482,27500,29499.670573,0.487936
2146,Cornerstone University,Grand Rapids,MI,2.0,2.0,0,1.0,6,Selective private,5,0.616904,0.0,0.319300,5537.0000,2200,0.476190,5260.1304,29400,32566.769514,0.504555
2147,Musicians Institute,Los Angeles,CA,4.0,3.0,0,1.0,10,Four-year for-profit,999,0.187683,0.0,0.011200,2961.0000,1204,0.428571,7081.0278,15500,25945.047526,0.440847
2148,Lagrange College,LaGrange,GA,3.0,2.0,0,1.0,6,Selective private,4,0.619048,0.0,0.416300,5532.0000,856,0.375000,10386.1700,39400,41308.714176,0.591175
2149,"International Business College of Fort Wayne, IN",Indianapolis,IN,2.0,3.0,0,2.0,11,Two-year for-profit,999,0.696565,0.0,0.170241,4504.0347,805,0.767469,3096.6077,27000,30466.933594,0.503815
2151,Lees-Mcrae College,Boone,NC,3.0,2.0,0,1.0,6,Selective private,4,0.533808,0.0,0.335200,4350.0000,890,0.384236,4181.0288,33100,37761.093750,0.556638
2154,Lincoln Christian University,Springfield,IL,2.0,2.0,0,1.0,8,Nonselective four-year private not-for-profit,999,0.519685,0.0,0.312500,5114.0000,623,0.450980,4242.0894,27700,30123.278646,0.510813
2155,William Woods University,Columbia,MO,2.0,2.0,0,1.0,6,Selective private,4,0.754348,0.0,0.248600,5301.0000,1002,0.564972,4261.9629,35000,36106.777263,0.553492
2159,Earlham College,Wayne,IN,2.0,2.0,0,1.0,6,Selective private,3,0.563126,0.0,0.363000,7391.0000,1064,0.710000,16590.3850,33300,38435.466146,0.544928
2162,Missouri Baptist University,St. Louis,MO,2.0,2.0,0,1.0,6,Selective private,4,0.608772,0.0,0.390500,5248.0000,3950,0.440678,2068.8105,34600,37089.303351,0.552311
2166,Erskine College,Greenville,SC,3.0,2.0,0,1.0,6,Selective private,4,0.599237,0.0,0.302700,5887.0000,605,0.564417,5711.3408,37400,45827.533854,0.606155
2167,Bluffton University,Lima,OH,2.0,2.0,0,1.0,6,Selective private,4,0.572840,0.0,0.469200,5189.0000,1053,0.597087,6801.6304,42400,43814.763021,0.599918
2168,Columbia International University,Columbia,SC,3.0,2.0,0,1.0,8,Nonselective four-year private not-for-profit,999,0.683983,0.0,0.374200,4559.0000,584,0.652174,5173.8364,18500,23138.324870,0.441342
2170,Santa Fe University Of Art And Design,Santa Fe,NM,4.0,3.0,0,1.0,10,Four-year for-profit,4,0.503497,0.0,0.002500,6682.0000,826,0.240964,8056.9854,32900,37164.167969,0.520290
2172,Lake Erie College,Cleveland,OH,2.0,2.0,0,1.0,6,Selective private,4,0.759843,0.0,0.443900,6327.0000,922,0.447257,4186.2930,31200,33984.568667,0.525821
2177,King University,Johnson City,TN,3.0,2.0,0,1.0,6,Selective private,3,0.632877,0.0,0.362300,4703.0000,2191,0.516484,4210.0859,37100,47819.189951,0.573326
2181,New Mexico Military Institute,Roswell,NM,4.0,1.0,1,2.0,9,Two-year (public and private not-for-profit),999,0.120930,0.0,0.581400,6852.0000,470,0.425076,12435.1220,49300,56607.401042,0.640480
2182,Kansas City Art Institute,Kansas City,MO,2.0,2.0,0,1.0,8,Nonselective four-year private not-for-profit,9,0.573984,0.0,0.357000,6008.0000,739,0.578947,8308.2461,25300,32850.756898,0.486230
2186,McNally Smith College Of Music,Minneapolis,MN,2.0,3.0,0,1.0,10,Four-year for-profit,999,0.159184,0.0,0.377900,4746.0000,576,0.484848,7058.2017,27400,34485.037760,0.514974
2193,Prism Career Institute,Philadelphia,PA,1.0,3.0,0,2.0,11,Two-year for-profit,999,0.875912,1.0,0.473839,1242.0000,816,0.917293,13274.8540,31000,25192.250651,0.463530
2197,Bel - Rea Institute Of Animal Technology,Denver,CO,4.0,3.0,0,2.0,11,Two-year for-profit,999,0.929907,0.0,0.324600,3988.0000,576,0.534091,4064.3665,29800,26469.069010,0.471147

In [312]:
Data=pd.read_csv('delta_public.csv')
Data.columns

Index(['groupid', 'academicyear', 'unitid_linchpin', 'unitid', 'isgrouped',
       'instname', 'TCSName', 'city', 'state', 'zip',
       ...
       'labor_share_of_instsuppcost', 'pubserv_sal_as_pct_pubservtot',
       'labor_share_of_pubservcost', 'assets06', 'liabilities07', 'assets11',
       'land04', 'buildings05', 'equipment05', 'assets15'],
      dtype='object', length=255)

In [313]:
Table_A

,super_opeid,name_x,czname_x,zip,state_x,region,type,public,iclevel,tier,...,female,multi,scorecard_rej_rate_2013,avgfacsal_2013,ipeds_enrollment_2013,grad_rate_150_p_2013,exp_instr_pc_2013,k_median_x,k_mean,k_rank
0,2665,Vaughn College Of Aeronautics And Technology,New York,11369,NY,1.0,2.0,0,1.0,8,...,0.099518,0.0,0.229400,9139.0000,1724,0.555556,5508.3994,53000,56313.276516,0.669554
1,7273,CUNY Bernard M. Baruch College,New York,10010,NY,1.0,1.0,1,1.0,5,...,0.551862,0.0,0.751700,8651.0000,14082,NaN,6754.6748,57600,69068.916604,0.698700
2,2688,City College Of New York - CUNY,New York,10031,NY,1.0,1.0,1,1.0,5,...,0.472238,0.0,0.659000,8257.0000,12501,0.476538,9341.7002,48500,60889.663557,0.659947
3,7022,CUNY Lehman College,New York,10468,NY,1.0,1.0,1,1.0,5,...,0.675445,0.0,0.767200,7271.0000,9886,NaN,7139.1030,40700,42720.624297,0.605398
4,1140,"California State University, Los Angeles",Los Angeles,90032,CA,4.0,1.0,1,1.0,5,...,0.624470,0.0,0.324800,8767.0000,19589,0.356537,4761.4780,43000,44225.554132,0.615710
5,2693,CUNY John Jay College Of Criminal Justice,New York,10019,NY,1.0,1.0,1,1.0,5,...,0.595277,0.0,0.659500,7339.0000,13217,NaN,6199.8784,45200,49034.965039,0.641264
6,2165,MCPHS University,Boston,2115,MA,1.0,2.0,0,1.0,8,...,0.706052,0.0,0.107900,8066.0000,3897,0.617450,9287.2422,112700,107741.835938,0.857008
7,2791,Pace University,New York,10038,NY,1.0,2.0,0,1.0,6,...,0.595074,0.0,0.231700,11627.0000,8289,0.514639,9327.0703,60700,68356.636178,0.705232
8,2838,State University Of New York At Stony Brook,New York,11794,NY,1.0,1.0,1,1.0,3,...,0.495815,0.0,0.605200,10346.0000,15992,0.659297,15185.5980,60100,65407.727703,0.708213
9,2696,New York City College Of Technology Of The Cit...,New York,11201,NY,1.0,1.0,1,1.0,5,...,0.445017,0.0,0.232000,6700.0000,16860,NaN,5951.1328,37000,39930.485043,0.575424
10,21662,ITI Technical College,Baton Rouge,70817,LA,3.0,3.0,0,2.0,11,...,0.086957,0.0,NaN,3693.0000,630,0.815126,4566.9126,55000,61562.876302,0.674412
11,9651,Texas A&M International University,Laredo,78041,TX,3.0,1.0,1,1.0,7,...,0.610465,0.0,0.521500,7689.0000,6585,0.429752,3503.4050,42800,44043.149851,0.620142
12,2687,CUNY Brooklyn College,New York,11210,NY,1.0,1.0,1,1.0,5,...,0.594256,0.0,0.680200,7529.0000,13596,NaN,6696.8579,44300,53799.113412,0.613695
13,11031,Technical Career Institutes,New York,10001,NY,1.0,3.0,0,2.0,11,...,0.261566,0.0,NaN,5582.0000,3020,0.240628,4798.6172,31300,36025.343400,0.530612
14,3599,University Of Texas - Pan American,Brownsville,78539,TX,3.0,1.0,1,1.0,5,...,0.557339,0.0,0.378300,7552.0000,17230,NaN,4907.6880,39300,41415.785656,0.588954
15,2689,CUNY Hunter College,New York,10065,NY,1.0,1.0,1,1.0,5,...,0.691808,0.0,0.702800,7895.0000,16689,NaN,6699.4121,44400,47546.281420,0.618232
16,25964,Crimson Technical College,Los Angeles,90301,CA,4.0,3.0,0,2.0,11,...,0.073718,0.0,NaN,NaN,458,0.756881,6492.1802,37600,41296.773438,0.614735
17,7405,Wood Tobe - Coburn School,New York,10016,NY,1.0,3.0,0,2.0,11,...,0.825581,0.0,NaN,5411.0000,476,0.810078,2262.9636,24500,29297.949870,0.485808
18,11189,United Talmudical Seminary,New York,11211,NY,1.0,2.0,0,1.0,8,...,0.013761,0.0,NaN,3624.0000,1814,0.432507,3026.6838,15300,25725.347656,0.426488
19,2690,CUNY Queens College,New York,11367,NY,1.0,1.0,1,1.0,5,...,0.612096,0.0,0.629800,7624.0000,15351,NaN,6069.6406,48200,55617.207264,0.629438
20,1203,Glendale Community College,Los Angeles,91208,CA,4.0,1.0,1,2.0,9,...,0.503363,0.0,NaN,8263.0000,15744,0.193248,2742.5244,30500,37418.350567,0.526280
21,31034,South Texas College,Brownsville,78502,TX,3.0,1.0,1,1.0,7,...,0.520376,0.0,NaN,5953.0000,31232,1.000000,1992.7892,27500,31900.772433,0.508007
22,1144,"California State Polytechnic University, Pomona",Los Angeles,91768,CA,4.0,1.0,1,1.0,5,...,0.420134,0.0,0.478200,9101.0000,20952,0.523726,5185.8892,55100,58449.621144,0.687875
23,3661,University Of Texas At El Paso,El Paso,79968,TX,3.0,1.0,1,1.0,5,...,0.524315,0.0,0.001900,8167.0000,19696,NaN,4914.3892,38400,41638.104486,0.586480
24,4759,CUNY York College,New York,11451,NY,1.0,1.0,1,1.0,5,...,0.681159,0.0,0.649000,7001.0000,8261,NaN,5785.8081,36400,40589.208531,0.569926
25,2823,"Saint John's University of Queens, NY",New York,11439,NY,1.0,2.0,0,1.0,6,...,0.562482,0.0,0.468400,11777.0000,15773,0.557262,7481.4761,58900,66248.341935,0.698639
26,1314,"University Of California, Irvine",Los Angeles,92697,CA,4.0,1.0,1,1.0,3,...,0.529847,0.0,0.576100,12839.0000,23530,0.858450,18460.7890,60400,68174.468984,0.705837
27,2812,Trocaire College,Buffalo,14220,NY,1.0,2.0,0,1.0,8,...,0.903030,0.0,0.031100,5215.0000,1492,NaN,5362.6250,38200,38036.402344,0.555252
28,20983,"Western Technical College of El Paso, TX",El Paso,79927,TX,3.0,3.0,0,2.0,11,...,0.256696,0.0,NaN,3282.4194,1466,0.545686,3140.0386,23900,30260.938802,0.489563
29,3582,Laredo Community College,Laredo,78040,TX,3.0,1.0,1,2.0,9,...,0.527041,0.0,NaN,5998.0000,8726,0.182975,2836.8154,28700,33508.652108,0.520009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2169,23427,"Fortis College of Richmond, VA",Richmond,23230,VA,3.0,3.0,0,2.0,11,...,NaN,0.0,NaN,5027.8359,1104,0.527872,11512.2710,16500,19718.532157,0.373859
2170,2649,Santa Fe University Of Art And Design,Santa Fe,87505,NM,4.0,3.0,0,1.0,10,...,0.503497,0.0,0.002500,6682.0000,826,0.240964,8056.9854,32900,37164.167969,0.520290
2171,21799,Argosy University,Los Angeles,92408,CA,4.0,3.0,0,1.0,10,...,0.929972,0.0,NaN,5450.9844,17881,0.348136,4034.0391,29700,31006.418461,0.515523
2172,3066,Lake Erie College,Cleveland,44077,OH,2.0,2.0,0,1.0,6,...,0.759843,0.0,0.443900,6327.0000,922,0.447257,4186.2930,31200,33984.568667,0.525821
2173,26009,Aveda Institute Covington,New Orleans,70433,LA,3.0,3.0,0,3.0,12,...,0.950820,0.0,NaN,NaN,1707,NaN,10242.2860,16200,16463.965495,0.358628
2174,32963,Baltimore School Of Massage,Baltimore,21090,MD,3.0,3.0,0,3.0,12,...,0.863014,0.0,NaN,NaN,357,NaN,5249.5928,19500,20455.733073,0.421220
2175,41143,Nevada State College,Las Vegas,89002,NV,4.0,1.0,1,1.0,7,...,NaN,0.0,0.496300,7570.0000,3377,0.137931,3025.3762,32900,35911.265625,0.531334
2176,25882,Douglas J Aveda Institute,Lansing,48823,MI,2.0,3.0,0,3.0,12,...,0.974026,0.0,NaN,NaN,977,NaN,3669.4873,21400,24965.737630,0.435304
2177,3496,King University,Johnson City,37620,TN,3.0,2.0,0,1.0,6,...,0.632877,0.0,0.362300,4703.0000,2191,0.516484,4210.0859,37100,47819.189951,0.573326
2178,4866,Stautzenberger College,Toledo,43537,OH,2.0,3.0,0,2.0,11,...,0.848039,0.0,NaN,3736.2412,1213,0.347230,3663.6848,17100,23348.893880,0.429964
2179,25318,"Paul Mitchell The School of Costa Mesa, CA",Los Angeles,92626,CA,4.0,3.0,0,3.0,12,...,0.922907,0.0,NaN,NaN,1492,0.772727,4390.1245,10300,17539.019531,0.368968
2180,4692,Dorsey School Of Business,Detroit,48066,MI,2.0,3.0,0,3.0,12,...,0.921296,0.0,NaN,NaN,1898,NaN,32577.4550,20600,21039.375651,0.419797
2181,2656,New Mexico Military Institute,Roswell,88201,NM,4.0,1.0,1,2.0,9,...,0.120930,0.0,0.581400,6852.0000,470,0.425076,12435.1220,49300,56607.401042,0.640480
2182,2473,Kansas City Art Institute,Kansas City,64111,MO,2.0,2.0,0,1.0,8,...,0.573984,0.0,0.357000,6008.0000,739,0.578947,8308.2461,25300,32850.756898,0.486230
2183,8178,"Empire Beauty School of Philadelphia, PA",Philadelphia,19102,PA,1.0,3.0,0,3.0,12,...,0.970833,0.0,NaN,NaN,1692,NaN,9003.4600,13200,16431.826497,0.364523
2184,10490,Regency Beauty Institute,Detroit,48195,MI,2.0,3.0,0,3.0,12,...,0.975207,0.0,NaN,NaN,6589,NaN,358895.4400,20000,22268.947116,0.422716
2185,21107,Cleveland Institute Of Dental - Medical Assist...,Cleveland,44060,OH,2.0,3.0,0,3.0,12,...,0.969697,0.0,NaN,NaN,312,NaN,27460.9710,14900,17892.596354,0.384350
2186,30012,McNally Smith College Of Music,Minneapolis,55101,MN,2.0,3.0,0,1.0,10,...,0.159184,0.0,0.377900,4746.0000,576,0.484848,7058.2017,27400,34485.037760,0.514974
2187,25326,Landmark College,Keene,5346,VT,1.0,2.0,0,1.0,8,...,0.333333,0.0,0.135300,5961.0000,494,NaN,12483.1290,21700,25616.019676,0.412665
2188,4645,Minneapolis Business College,Minneapolis,55113,MN,2.0,3.0,0,2.0,11,...,0.743333,0.0,NaN,4494.0000,273,0.850649,3127.4980,41400,37344.252604,0.577707
2189,1929,Kansas Wesleyan University,Salina,67401,KS,2.0,2.0,0,1.0,6,...,NaN,0.0,0.463000,5498.0000,684,0.427273,4623.1733,41000,41670.213980,0.607400
2190,23269,Sunstate Academy,Cape Coral,33907,FL,3.0,3.0,0,3.0,12,...,0.857895,0.0,NaN,NaN,355,NaN,1634.3220,17000,20810.433085,0.392714
2191,30987,"Milan Institute of Palm Desert, CA",Los Angeles,92211,CA,4.0,3.0,0,3.0,12,...,0.886364,0.0,NaN,NaN,434,NaN,3719.3218,19000,15524.988607,0.372605
2192,9459,"Empire Beauty School of Portland, ME",Portland,4101,ME,1.0,3.0,0,3.0,12,...,0.951872,0.0,NaN,NaN,1730,0.425532,9118.9756,11300,15191.159831,0.355832
2193,118,Prism Career Institute,Philadelphia,19082,PA,1.0,3.0,0,2.0,11,...,0.875912,1.0,0.473839,1242.0000,816,0.917293,13274.8540,31000,25192.250651,0.463530
2194,112,Capri Institute Of Hair Design,Newark,7011,NJ,1.0,3.0,0,3.0,12,...,0.905405,1.0,NaN,NaN,593,NaN,5335.4429,18300,23657.132302,0.425306
2195,3672,Latter Day Saints Business College,Salt Lake City,84101,UT,4.0,2.0,0,2.0,9,...,0.592668,0.0,NaN,6358.0000,2036,0.307175,2337.7454,29900,29154.603516,0.463034
2196,54,Midred Elley College And Austin's School Of Sp...,Albany,12206,NY,1.0,3.0,0,2.0,11,...,0.814346,1.0,NaN,4391.5698,1987,0.335079,9774.3213,12700,17774.585286,0.374174
2197,12670,Bel - Rea Institute Of Animal Technology,Denver,80247,CO,4.0,3.0,0,2.0,11,...,0.929907,0.0,0.324600,3988.0000,576,0.534091,4064.3665,29800,26469.069010,0.471147
2198,30086,Florida College Of Natural Health,Orlando,32751,FL,3.0,3.0,0,2.0,11,...,0.875000,0.0,NaN,3628.5298,970,0.723145,17974.8870,16200,19082.808594,0.401833

In [314]:
Data_2012=Data.loc[Data['academicyear']==2012]

In [315]:
Data_2012=Data_2012.rename(columns={"instname": "name_x"})

In [316]:
Data_2012_A=Data_2012[['name_x','cpi_index','oberegion','carnegie2010','flagship',
      'medical','hospital','fte_count','fte12mn',
      'tuition01_tf','tuitionfee01_tf','tuition05_tf','tuitionfee05_tf',
     'instruction01','grants01']]

In [317]:
Table_B=Table_A.merge(Data_2012_A, on='name_x', how='left')

In [318]:
Table_B.columns

Index(['super_opeid', 'name_x', 'czname_x', 'zip', 'state_x', 'region', 'type',
       'public', 'iclevel', 'tier', 'tier_name', 'barrons', 'female', 'multi',
       'scorecard_rej_rate_2013', 'avgfacsal_2013', 'ipeds_enrollment_2013',
       'grad_rate_150_p_2013', 'exp_instr_pc_2013', 'k_median_x', 'k_mean',
       'k_rank', 'cpi_index', 'oberegion', 'carnegie2010', 'flagship',
       'medical', 'hospital', 'fte_count', 'fte12mn', 'tuition01_tf',
       'tuitionfee01_tf', 'tuition05_tf', 'tuitionfee05_tf', 'instruction01',
       'grants01'],
      dtype='object')

In [319]:
Table_B.count()

super_opeid                2207
name_x                     2207
czname_x                   2207
zip                        2207
state_x                    2207
region                     2207
type                       2207
public                     2207
iclevel                    2207
tier                       2207
tier_name                  2207
barrons                    2207
female                     2188
multi                      2207
scorecard_rej_rate_2013    1236
avgfacsal_2013             2134
ipeds_enrollment_2013      2207
grad_rate_150_p_2013       2034
exp_instr_pc_2013          2201
k_median_x                 2207
k_mean                     2207
k_rank                     2207
cpi_index                   996
oberegion                   996
carnegie2010                996
flagship                    996
medical                     996
hospital                    996
fte_count                   993
fte12mn                     993
tuition01_tf                973
tuitionfee01_tf             973
tuition05_tf                446
tuitionfee05_tf             446
instruction01               994
grants01                    582
dtype: int64

In [329]:
Table_B.loc[Table_B['tier']==2,:]

,super_opeid,name_x,czname_x,zip,state_x,region,type,public,iclevel,tier,...,medical,hospital,fte_count,fte12mn,tuition01_tf,tuitionfee01_tf,tuition05_tf,tuitionfee05_tf,instruction01,grants01
48,1315,"University Of California, Los Angeles",Los Angeles,90095,CA,4.0,1.0,1,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,2710,Cooper Union For The Advancement Of Science & ...,New York,10003,NY,1.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,1328,University Of Southern California,Los Angeles,90089,CA,4.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,2785,New York University,New York,10012,NY,1.0,2.0,0,1.0,2,...,1.0,2.0,37922.0,44278.0,39344.0,41606.0,33168.0,35420.0,1.104353e+09,NaN
179,2708,Barnard College,New York,10027,NY,1.0,2.0,0,1.0,2,...,2.0,2.0,2408.0,2334.0,40422.0,42184.0,NaN,NaN,4.697176e+07,NaN
200,1249,Occidental College,Los Angeles,90041,CA,4.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,1131,California Institute Of Technology,Los Angeles,91125,CA,4.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,2803,Rensselaer Polytechnic Institute,Albany,12180,NY,1.0,2.0,0,1.0,2,...,2.0,2.0,6452.0,6787.0,41600.0,42704.0,41600.0,43496.0,1.080930e+08,11595000.0
272,2894,University Of Rochester,Buffalo,14627,NY,1.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,1536,University Of Miami,Miami,33146,FL,3.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,1170,Claremont Mckenna College,Los Angeles,91711,CA,4.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,1171,Harvey Mudd College,Los Angeles,91711,CA,4.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,1174,Scripps College,Los Angeles,91711,CA,4.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
459,2224,Wellesley College,Boston,2481,MA,1.0,2.0,0,1.0,2,...,2.0,2.0,2422.0,2627.0,40410.0,40660.0,NaN,NaN,7.472200e+07,NaN
500,2728,Hamilton College,Syracuse,13323,NY,1.0,2.0,0,1.0,2,...,2.0,2.0,1852.0,1831.0,42220.0,42640.0,NaN,NaN,4.373600e+07,NaN
509,3370,Swarthmore College,Philadelphia,19081,PA,1.0,2.0,0,1.0,2,...,2.0,2.0,1540.0,1566.0,40816.0,41150.0,NaN,NaN,3.807583e+07,NaN
541,1830,Rose - Hulman Institute Of Technology,Terre Haute,47803,IN,2.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,3242,Carnegie Mellon University,Pittsburgh,15213,PA,1.0,2.0,0,1.0,2,...,2.0,2.0,10871.0,10882.0,43160.0,44010.0,36900.0,37542.0,3.198448e+08,NaN
568,1444,George Washington University,Washington DC,20052,DC,3.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
574,2077,Johns Hopkins University,Baltimore,21218,MD,3.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,2219,Tufts University,Boston,2155,MA,1.0,2.0,0,1.0,2,...,1.0,2.0,10227.0,11139.0,41998.0,42962.0,41208.0,41916.0,1.932939e+08,NaN
639,2133,Brandeis University,Boston,2454,MA,1.0,2.0,0,1.0,2,...,2.0,2.0,5517.0,6614.0,40514.0,41860.0,40514.0,40584.0,1.174777e+08,NaN
695,1424,Wesleyan University,Bridgeport,6459,CT,1.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,2115,Amherst College,Springfield,1002,MA,1.0,2.0,0,1.0,2,...,2.0,2.0,1791.0,1931.0,42170.0,42898.0,NaN,NaN,4.129710e+07,806370.0
716,1173,Pomona College,Los Angeles,91711,CA,4.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,1445,Georgetown University,Washington DC,20057,DC,3.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
765,3289,Lehigh University,Allentown,18015,PA,1.0,2.0,0,1.0,2,...,2.0,2.0,6356.0,6466.0,40660.0,40960.0,21960.0,21960.0,1.095510e+08,NaN
803,3237,Bryn Mawr College,Philadelphia,19010,PA,1.0,2.0,0,1.0,2,...,2.0,2.0,1699.0,1777.0,39860.0,40824.0,34110.0,34110.0,3.761600e+07,NaN
820,2642,College Of New Jersey,Newark,8628,NJ,1.0,1.0,1,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
824,1564,Emory University,Atlanta,30322,GA,3.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,3604,Rice University,Houston,77005,TX,3.0,2.0,0,1.0,2,...,2.0,2.0,6083.0,6388.0,34900.0,35551.0,29730.0,30232.0,2.147410e+08,12726311.0
1010,2128,Boston College,Boston,2467,MA,1.0,2.0,0,1.0,2,...,2.0,2.0,13806.0,13888.0,41480.0,42204.0,22356.0,22446.0,2.184596e+08,NaN
1031,1379,Connecticut College,Bridgeport,6320,CT,1.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1147,3535,Vanderbilt University,Nashville,37240,TN,3.0,2.0,0,1.0,2,...,1.0,1.0,12274.0,11729.0,40320.0,41332.0,40320.0,40718.0,8.234308e+08,NaN
1160,3745,University Of Virginia,Charlottesville,22903,VA,3.0,1.0,1,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1161,3238,Bucknell University,Sunbury,17837,PA,1.0,2.0,0,1.0,2,...,2.0,2.0,3604.0,3705.0,43628.0,43866.0,19160.0,19160.0,5.936500e+07,NaN
1238,2358,Macalester College,Minneapolis,55105,MN,2.0,2.0,0,1.0,2,...,2.0,2.0,1989.0,1992.0,41800.0,42000.0,NaN,NaN,3.257900e+07,NaN
1275,2340,Carleton College,Owatonna,55057,MN,2.0,2.0,0,1.0,2,...,2.0,2.0,2008.0,1962.0,42690.0,42942.0,NaN,NaN,4.342056e+07,NaN
1333,3388,Villanova University,Philadelphia,19085,PA,1.0,2.0,0,1.0,2,...,2.0,2.0,9012.0,10064.0,40530.0,41110.0,14877.0,14937.0,1.363649e+08,NaN
1392,3691,Middlebury College,Burlington,5753,VT,1.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1405,3265,Franklin & Marshall College,Reading,17604,PA,1.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1416,3086,Oberlin College,Lorain,44074,OH,2.0,2.0,0,1.0,2,...,2.0,2.0,2946.0,2963.0,42842.0,43210.0,35559.0,35927.0,6.682226e+07,NaN
1523,2974,University Of North Carolina - Chapel Hill,Raleigh,27599,NC,3.0,1.0,1,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1531,3217,Reed College,Portland,97202,OR,4.0,2.0,0,1.0,2,...,2.0,2.0,1442.0,1448.0,42540.0,42800.0,NaN,NaN,2.804142e+07,NaN
1583,2038,Bowdoin College,Portland,4011,ME,1.0,2.0,0,1.0,2,...,2.0,2.0,1775.0,1788.0,42386.0,42816.0,NaN,NaN,3.893199e+07,NaN
1584,2895,Vassar College,Poughkeepsie,12604,NY,1.0,2.0,0,1.0,2,...,2.0,2.0,2361.0,2432.0,44050.0,44705.0,44050.0,44705.0,5.942723e+07,NaN
1645,2520,Washington University In St. Louis,St. Louis,63130,MO,2.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1687,2141,College Of The Holy Cross,Boston,1610,MA,1.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1712,2229,Williams College,Pittsfield,1267,MA,1.0,2.0,0,1.0,2,...,2.0,2.0,2101.0,2128.0,42938.0,43190.0,43500.0,43500.0,7.267240e+07,NaN
1809,2039,Colby College,Portland,4901,ME,1.0,2.0,0,1.0,2,...,2.0,2.0,1815.0,1820.0,41020.0,42820.0,NaN,NaN,3.398000e+07,NaN
1818,1840,University Of Notre Dame,South Bend,46556,IN,2.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1832,3803,Whitman College,Kennewick,99362,WA,4.0,2.0,0,1.0,2,...,2.0,2.0,1578.0,1525.0,40180.0,40496.0,NaN,NaN,2.190051e+07,NaN
1843,2701,Colgate University,Syracuse,13346,NY,1.0,2.0,0,1.0,2,...,2.0,2.0,2946.0,2928.0,42625.0,42920.0,42625.0,42920.0,4.545117e+07,NaN
1955,2036,Bates College,Portland,4240,ME,1.0,2.0,0,1.0,2,...,2.0,2.0,1769.0,1755.0,42550.0,42800.0,NaN,NaN,3.081839e+07,NaN
1979,2978,Wake Forest University,Winston-Salem,27106,NC,3.0,2.0,0,1.0,2,...,1.0,2.0,7269.0,7272.0,41100.0,41576.0,32208.0,32534.0,1.739460e+08,NaN
2033,3065,Kenyon College,Columbus,43022,OH,2.0,2.0,0,1.0,2,...,2.0,2.0,1652.0,1861.0,41090.0,42630.0,NaN,NaN,3.008026e+07,NaN
2035,3744,University Of Richmond,Richmond,23173,VA,3.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2076,3768,Washington And Lee University,Staunton,24450,VA,3.0,2.0,0,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2104,3705,College Of William & Mary,Newport News,23187,VA,3.0,1.0,1,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2138,2918,Davidson College,Charlotte,28035,NC,3.0,2.0,0,1.0,2,...,2.0,2.0,1755.0,1915.0,38481.0,38866.0,NaN,NaN,3.112842e+07,NaN

In [328]:
Table_A.loc[Table_A['tier']==1,:]

,super_opeid,name_x,czname_x,zip,state_x,region,type,public,iclevel,tier,...,female,multi,scorecard_rej_rate_2013,avgfacsal_2013,ipeds_enrollment_2013,grad_rate_150_p_2013,exp_instr_pc_2013,k_median_x,k_mean,k_rank
191,2178,Massachusetts Institute Of Technology,Boston,2139,MA,1.0,2.0,0,1.0,1,...,0.428102,0.0,0.9185,15617.0,4528,0.930712,42687.906,98500,168951.477760,0.812153
260,2707,Columbia University In The City Of New York,New York,10027,NY,1.0,2.0,0,1.0,1,...,0.455934,0.0,0.9258,15706.0,7970,0.932896,71529.219,75300,128030.685244,0.752043
303,2711,Cornell University,Elmira,14853,NY,1.0,2.0,0,1.0,1,...,0.483735,0.0,0.8444,13820.0,14393,0.933444,21218.816,79800,117283.222940,0.774410
527,1305,Stanford University,San Jose,94305,CA,4.0,2.0,0,1.0,1,...,0.507144,0.0,0.9431,19862.0,7274,0.957583,67758.086,84800,174059.045302,0.774627
608,1426,Yale University,Bridgeport,6520,CT,1.0,2.0,0,1.0,1,...,0.506612,0.0,0.9295,16042.0,5430,0.977913,112324.660,76000,143231.283910,0.761393
625,3378,University Of Pennsylvania,Philadelphia,19104,PA,1.0,2.0,0,1.0,1,...,0.496858,0.0,0.8776,15460.0,11525,0.956874,42942.691,91800,172802.519674,0.791496
720,1774,University Of Chicago,Chicago,60637,IL,2.0,2.0,0,1.0,1,...,0.508372,0.0,0.9119,16589.0,5703,0.926754,60602.469,61700,92628.021247,0.719397
854,129,Harvard University,Boston,2138,MA,1.0,2.0,0,1.0,1,...,0.468517,0.0,0.9416,17861.0,10534,0.974653,34848.566,81500,170575.240401,0.767807
1008,2920,Duke University,Raleigh,27708,NC,3.0,2.0,0,1.0,1,...,0.487111,0.0,0.8658,14288.0,6646,0.942319,55339.918,87500,139638.250368,0.787622
1063,3401,Brown University,Providence,2912,RI,1.0,2.0,0,1.0,1,...,0.537272,0.0,0.9082,13381.0,6455,0.945159,28680.811,66900,106812.805377,0.736429
1254,2573,Dartmouth College,Claremont,3755,NH,1.0,2.0,0,1.0,1,...,0.481928,0.0,0.9022,13143.0,4276,0.947038,21772.873,76600,130760.100925,0.766836
1294,2627,Princeton University,Newark,8544,NJ,1.0,2.0,0,1.0,1,...,0.480857,0.0,0.9259,15711.0,5323,0.969429,37336.176,90700,166992.690795,0.790548

In [327]:
Data_2012.loc[Data_2012['name_x'].str.contains('Pennsylvania'),:]

,groupid,academicyear,unitid_linchpin,unitid,isgrouped,name_x,TCSName,city,state,zip,...,labor_share_of_instsuppcost,pubserv_sal_as_pct_pubservtot,labor_share_of_pubservcost,assets06,liabilities07,assets11,land04,buildings05,equipment05,assets15
4124,-445799,2012,445799,445799,0,Universal Technical Institute of Pennsylvania Inc,NaN,Exton,PA,19341,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5175,-443784,2012,443784,443784,0,Strayer University-Pennsylvania,NaN,Trevose,PA,19053,...,NaN,NaN,NaN,1.824378e+07,1.096859e+07,NaN,NaN,NaN,NaN,NaN
15025,-414911,2012,414911,414911,0,Pennsylvania Highlands Community College,Pennsylvania Highlands Community College,Johnstown,PA,15904,...,0.525208,NaN,NaN,1.476161e+07,4.450382e+06,1.031123e+07,NaN,NaN,NaN,1.031123e+07
21690,-369668,2012,369668,369668,0,Central Pennsylvania Institute of Science and ...,NaN,Pleasant Gap,PA,16823,...,1.049776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22697,-366252,2012,366252,366252,0,Pennsylvania College of Technology,Pennsylvania College of Technology,Williamsport,PA,17701-5799,...,0.487585,NaN,NaN,2.455850e+08,1.664810e+08,7.910394e+07,25244559.0,NaN,NaN,7.910394e+07
35792,-217059,2012,217059,217059,0,York College Pennsylvania,York College Pennsylvania,York,PA,17403-3651,...,0.608150,0.613164,0.827467,3.915378e+08,1.229952e+08,2.685426e+08,12013742.0,NaN,NaN,2.685426e+08
35902,-216773,2012,216773,216773,0,Western Pennsylvania Hospital School of Nursing,NaN,Pittsburgh,PA,15224,...,0.925102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35915,-216764,2012,216764,216764,0,West Chester University of Pennsylvania,West Chester University of Pennsylvania,West Chester,PA,19383,...,0.601944,0.462512,0.674571,3.907192e+08,2.281513e+08,1.625679e+08,26208791.0,NaN,NaN,1.625679e+08
36279,-216038,2012,216038,216038,0,Slippery Rock University of Pennsylvania,Slippery Rock University of Pennsylvania,Slippery Rock,PA,16057-1383,...,0.453041,0.344758,0.517804,2.178474e+08,1.555459e+08,6.230150e+07,13202808.0,NaN,NaN,6.230150e+07
36292,-216010,2012,216010,216010,0,Shippensburg University of Pennsylvania,Shippensburg University of Pennsylvania,Shippensburg,PA,17257-2299,...,0.647324,0.251785,0.372977,2.222613e+08,1.457922e+08,7.646912e+07,13780922.0,NaN,NaN,7.646912e+07
36757,-215062,2012,215062,215062,0,University of Pennsylvania,University of Pennsylvania,Philadelphia,PA,19104-6303,...,0.806119,0.240829,0.302400,1.470260e+10,5.008974e+09,9.693626e+09,151731000.0,NaN,NaN,9.693626e+09
36770,-215053,2012,215053,215053,0,Pennsylvania College of Art and Design,NaN,Lancaster,PA,17608-0059,...,0.608528,NaN,NaN,1.348844e+07,3.248364e+06,1.024007e+07,82508.0,NaN,NaN,1.024007e+07
36781,-215044,2012,215044,215044,0,Cortiva Institute-Pennsylvania School of Muscl...,NaN,King of Prussia,PA,19406,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36797,-215026,2012,215026,215026,0,Pennsylvania Institute of Taxidermy Inc,NaN,Ebensburg,PA,15931-4106,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36810,-215008,2012,215008,215008,0,Pennsylvania Gunsmith School,NaN,Pittsburgh,PA,15202-2637,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36823,-214971,2012,214971,214971,0,Pennsylvania Academy of the Fine Arts,NaN,Philadelphia,PA,19102-1510,...,0.021615,NaN,NaN,7.591952e+07,2.431660e+07,5.160292e+07,2500000.0,NaN,NaN,5.160292e+07
36836,-214962,2012,214962,214962,0,Pennsylvania Academy of Cosmetology Arts and S...,NaN,Du Bois,PA,15801,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36903,-214661,2012,214661,214661,0,Pennsylvania State System of Higher Education-...,NaN,Harrisburg,PA,17110,...,0.652164,NaN,NaN,7.528974e+07,3.997563e+07,3.531411e+07,1807341.0,NaN,NaN,3.531411e+07
36916,-214582,2012,214582,214582,0,Pennsylvania Institute of Technology,NaN,Media,PA,19063-4098,...,0.838666,NaN,NaN,1.325890e+07,1.083780e+07,2.421098e+06,836810.0,NaN,NaN,2.421098e+06
36942,-214546,2012,214546,214546,0,Pennsylvania Academy of Cosmetology Arts and S...,NaN,Johnstown,PA,15904-1499,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37085,-214041,2012,214041,214041,0,Millersville University of Pennsylvania,Millersville University of Pennsylvania,Millersville,PA,17551-0302,...,0.566686,0.215472,0.314001,2.413090e+08,1.652477e+08,7.606136e+07,19154816.0,NaN,NaN,7.606136e+07
37187,-213783,2012,213783,213783,0,Mansfield University of Pennsylvania,Mansfield University of Pennsylvania,Mansfield,PA,16933,...,0.667033,0.317391,0.475075,7.633523e+07,6.656350e+07,9.771733e+06,9335210.0,NaN,NaN,9.771733e+06
37288,-213598,2012,213598,213598,0,Lincoln University of Pennsylvania,Lincoln University of Pennsylvania,Lincoln University,PA,19352-0999,...,0.539575,NaN,NaN,2.511791e+08,4.322000e+07,2.079591e+08,906161.0,NaN,NaN,2.079591e+08
37511,-213349,2012,213349,213349,0,Kutztown University of Pennsylvania,Kutztown University of Pennsylvania,Kutztown,PA,19530-0730,...,0.437626,0.386343,0.581618,3.683694e+08,2.548048e+08,1.135646e+08,13432874.0,NaN,NaN,1.135646e+08
37634,-213057,2012,213057,213057,0,Pennsylvania School of Business,NaN,Allentown,PA,18101-1604,...,NaN,NaN,NaN,2.210038e+06,9.850490e+05,NaN,NaN,NaN,NaN,NaN
38106,-212160,2012,212160,212160,0,Edinboro University of Pennsylvania,Edinboro University of Pennsylvania,Edinboro,PA,16444-0001,...,0.520798,0.404524,0.609317,1.447653e+08,1.298478e+08,1.491756e+07,511567.0,NaN,NaN,1.491756e+07
38139,-212115,2012,212115,212115,0,East Stroudsburg University of Pennsylvania,East Stroudsburg University of Pennsylvania,East Stroudsburg,PA,18301-2999,...,0.429414,0.312713,0.458871,1.793944e+08,1.399223e+08,3.947208e+07,28192528.0,NaN,NaN,3.947208e+07
38370,-211608,2012,211608,211608,0,Cheyney University of Pennsylvania,Cheyney University of Pennsylvania,Cheyney,PA,19319-0200,...,0.530520,NaN,NaN,4.150951e+07,4.936933e+07,-7.859818e+06,5087235.0,NaN,NaN,-7.859818e+06
38491,-211361,2012,211361,211361,0,California University of Pennsylvania,California University of Pennsylvania,California,PA,15419-1394,...,0.578874,0.413469,0.603451,1.895983e+08,1.871307e+08,2.467622e+06,33576913.0,NaN,NaN,2.467622e+06
38607,-211158,2012,211158,211158,0,Bloomsburg University of Pennsylvania,Bloomsburg University of Pennsylvania,Bloomsburg,PA,17815,...,0.585761,0.406159,0.598552,2.534697e+08,1.790462e+08,7.442358e+07,20204228.0,NaN,NaN,7.442358e+07